name: adaptive_settings
description: Settings UI package for flutter
version: 0.0.1
homepage: https://github.com/phamdanh/Adaptive-Settings
repository: https://github.com/phamdanh/Adaptive-Settings

environment:
  sdk: '>=3.0.5 <4.0.0'
  flutter: ">=3.3.0"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.dp.adaptive_settings
        pluginClass: AdaptiveSettingsPlugin
      ios:
        pluginClass: AdaptiveSettingsPlugin
      macos:
        pluginClass: AdaptiveSettingsPlugin
      windows:
        pluginClass: AdaptiveSettingsPluginCApi
